{"content": {"suites": {"0": {"status": {"total_pass": 2, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 1}, "tests": {"0": {"status": "ERROR", "message": "self = <mysql.connector.connection_cext.CMySQLConnection object at 0x74f479f58670>\n\n    def _open_connection(self) -> None:\n        charset_name = self._character_set.get_info(self._charset_id)[0]\n        # pylint: disable=c-extension-no-member\n        self._cmysql = _mysql_connector.MySQL(\n            buffered=self._buffered,\n            raw=self._raw,\n            charset_name=charset_name,\n            connection_timeout=(self._connection_timeout or 0),\n            use_unicode=self._use_unicode,\n            auth_plugin=self._auth_plugin,\n            plugin_dir=self._plugin_dir,\n        )\n        # pylint: enable=c-extension-no-member\n        if not self.isset_client_flag(ClientFlag.CONNECT_ARGS):\n            self._conn_attrs = {}\n    \n        cnx_kwargs = {\n            \"host\": self._host,\n            \"user\": self._user,\n            \"password\": self._password,\n            \"password1\": self._password1,\n            \"password2\": self._password2,\n            \"password3\": self._password3,\n            \"database\": self._database,\n            \"port\": self._port,\n            \"client_flags\": self._client_flags,\n            \"unix_socket\": self._unix_socket,\n            \"compress\": self._compress,\n            \"ssl_disabled\": True,\n            \"conn_attrs\": self._conn_attrs,\n            \"local_infile\": self._allow_local_infile,\n            \"load_data_local_dir\": self._allow_local_infile_in_path,\n            \"oci_config_file\": self._oci_config_file,\n            \"oci_config_profile\": self._oci_config_profile,\n            \"webauthn_callback\": (\n                import_object(self._webauthn_callback)\n                if isinstance(self._webauthn_callback, str)\n                else self._webauthn_callback\n            ),\n        }\n    \n        tls_versions = self._ssl.get(\"tls_versions\")\n        if tls_versions is not None:\n            tls_versions.sort(reverse=True)  # type: ignore[union-attr]\n            tls_versions = \",\".join(tls_versions)\n        if self._ssl.get(\"tls_ciphersuites\") is not None:\n            ssl_ciphersuites = self._ssl.get(\"tls_ciphersuites\")[  # type: ignore[index]\n                0\n            ]\n            tls_ciphersuites = self._ssl.get(\"tls_ciphersuites\")[  # type: ignore[index]\n                1\n            ]\n        else:\n            ssl_ciphersuites = None\n            tls_ciphersuites = None\n        if (\n            tls_versions is not None\n            and \"TLSv1.3\" in tls_versions\n            and not tls_ciphersuites\n        ):\n            tls_ciphersuites = \"TLS_AES_256_GCM_SHA384\"\n        if not self._ssl_disabled:\n            cnx_kwargs.update(\n                {\n                    \"ssl_ca\": self._ssl.get(\"ca\"),\n                    \"ssl_cert\": self._ssl.get(\"cert\"),\n                    \"ssl_key\": self._ssl.get(\"key\"),\n                    \"ssl_cipher_suites\": ssl_ciphersuites,\n                    \"tls_versions\": tls_versions,\n                    \"tls_cipher_suites\": tls_ciphersuites,\n                    \"ssl_verify_cert\": self._ssl.get(\"verify_cert\") or False,\n                    \"ssl_verify_identity\": self._ssl.get(\"verify_identity\") or False,\n                    \"ssl_disabled\": self._ssl_disabled,\n                }\n            )\n    \n        if os.name == \"nt\" and self._auth_plugin_class == \"MySQLKerberosAuthPlugin\":\n            cnx_kwargs[\"use_kerberos_gssapi\"] = True\n    \n        try:\n>           self._cmysql.connect(**cnx_kwargs)\nE           _mysql_connector.MySQLInterfaceError: Access denied for user 'root'@'localhost' (using password: YES)\n\n../../.venv/lib/python3.10/site-packages/mysql/connector/connection_cext.py:334: MySQLInterfaceError\n\nThe above exception was the direct cause of the following exception:\n\n    @pytest.fixture\n    def get_connection():\n>       my_db = mysql.connector.connect(\n            host='localhost',\n            user='root',\n            password='n4pb*Fn785',\n            database='fortis'\n        )\n\ntest_db.py:6: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n../../.venv/lib/python3.10/site-packages/mysql/connector/pooling.py:322: in connect\n    return CMySQLConnection(*args, **kwargs)\n../../.venv/lib/python3.10/site-packages/mysql/connector/connection_cext.py:151: in __init__\n    self.connect(**kwargs)\n../../.venv/lib/python3.10/site-packages/mysql/connector/abstracts.py:1399: in connect\n    self._open_connection()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <mysql.connector.connection_cext.CMySQLConnection object at 0x74f479f58670>\n\n    def _open_connection(self) -> None:\n        charset_name = self._character_set.get_info(self._charset_id)[0]\n        # pylint: disable=c-extension-no-member\n        self._cmysql = _mysql_connector.MySQL(\n            buffered=self._buffered,\n            raw=self._raw,\n            charset_name=charset_name,\n            connection_timeout=(self._connection_timeout or 0),\n            use_unicode=self._use_unicode,\n            auth_plugin=self._auth_plugin,\n            plugin_dir=self._plugin_dir,\n        )\n        # pylint: enable=c-extension-no-member\n        if not self.isset_client_flag(ClientFlag.CONNECT_ARGS):\n            self._conn_attrs = {}\n    \n        cnx_kwargs = {\n            \"host\": self._host,\n            \"user\": self._user,\n            \"password\": self._password,\n            \"password1\": self._password1,\n            \"password2\": self._password2,\n            \"password3\": self._password3,\n            \"database\": self._database,\n            \"port\": self._port,\n            \"client_flags\": self._client_flags,\n            \"unix_socket\": self._unix_socket,\n            \"compress\": self._compress,\n            \"ssl_disabled\": True,\n            \"conn_attrs\": self._conn_attrs,\n            \"local_infile\": self._allow_local_infile,\n            \"load_data_local_dir\": self._allow_local_infile_in_path,\n            \"oci_config_file\": self._oci_config_file,\n            \"oci_config_profile\": self._oci_config_profile,\n            \"webauthn_callback\": (\n                import_object(self._webauthn_callback)\n                if isinstance(self._webauthn_callback, str)\n                else self._webauthn_callback\n            ),\n        }\n    \n        tls_versions = self._ssl.get(\"tls_versions\")\n        if tls_versions is not None:\n            tls_versions.sort(reverse=True)  # type: ignore[union-attr]\n            tls_versions = \",\".join(tls_versions)\n        if self._ssl.get(\"tls_ciphersuites\") is not None:\n            ssl_ciphersuites = self._ssl.get(\"tls_ciphersuites\")[  # type: ignore[index]\n                0\n            ]\n            tls_ciphersuites = self._ssl.get(\"tls_ciphersuites\")[  # type: ignore[index]\n                1\n            ]\n        else:\n            ssl_ciphersuites = None\n            tls_ciphersuites = None\n        if (\n            tls_versions is not None\n            and \"TLSv1.3\" in tls_versions\n            and not tls_ciphersuites\n        ):\n            tls_ciphersuites = \"TLS_AES_256_GCM_SHA384\"\n        if not self._ssl_disabled:\n            cnx_kwargs.update(\n                {\n                    \"ssl_ca\": self._ssl.get(\"ca\"),\n                    \"ssl_cert\": self._ssl.get(\"cert\"),\n                    \"ssl_key\": self._ssl.get(\"key\"),\n                    \"ssl_cipher_suites\": ssl_ciphersuites,\n                    \"tls_versions\": tls_versions,\n                    \"tls_cipher_suites\": tls_ciphersuites,\n                    \"ssl_verify_cert\": self._ssl.get(\"verify_cert\") or False,\n                    \"ssl_verify_identity\": self._ssl.get(\"verify_identity\") or False,\n                    \"ssl_disabled\": self._ssl_disabled,\n                }\n            )\n    \n        if os.name == \"nt\" and self._auth_plugin_class == \"MySQLKerberosAuthPlugin\":\n            cnx_kwargs[\"use_kerberos_gssapi\"] = True\n    \n        try:\n            self._cmysql.connect(**cnx_kwargs)\n            self._cmysql.converter_str_fallback = self._converter_str_fallback\n            if self.converter:\n                self.converter.str_fallback = self._converter_str_fallback\n        except MySQLInterfaceError as err:\n>           raise get_mysql_exception(\n                msg=err.msg, errno=err.errno, sqlstate=err.sqlstate\n            ) from err\nE           mysql.connector.errors.ProgrammingError: 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)\n\n../../.venv/lib/python3.10/site-packages/mysql/connector/connection_cext.py:339: ProgrammingError\n", "test_name": "test_create_record", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_a2", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_a3", "rerun": "0"}}, "suite_name": "test_db.py"}}}, "date": "July 08, 2024", "start_time": 1720415301.7034872, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "2", "fail": "0", "skip": "0", "error": "1", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "3"}